### ISSUE TITLE
About Language-guided Generation, could you please tell me some details?

### ISSUE THREAD

**Issue by LIJIAQI1999** [colorful-liyu/3DQD#11]
Hi, colorful-liyu!Great work!
I want to ensure some details about language-guided generation.

First, for each text in the test split of ShapeGlot, how many samples are generated (one text with one sample or one text with multiple samples)?

Second, how many samples in total are generated? Are texts from ShapeGlot fully used or just part of them is used?

At last, could you share me your hyperparameters config? I'm not sure that whether the config in the code is the same as yours. And I can not get the same metric values using the default config in your code.

Appreciate for your helps! Wish you all the best!

**Comment by colorful-liyu** [comment]
Hi.
1.  For each text prompt, we generated 9 shapes, because we not only report the generation quality but diversity as well.
3.  It's 500. It's only a subset of official test splits. Because evaluating on the whole ShapeGlot is costly for us.
4.  I use the same hyperparameters in the default config of `eval_textdf.py`. 

I guess the different metric values come from the different test subset samples. We use a random seed to select the first 500 samples in the test split of ShapeGlot to evaluate our model and baselines. I could provide the detailed text subset we use if you need it.

Besides, even with the same test subset and hyperparameters, it's still possible to get slightly different results due to randomness in the diffusing process.

**Comment by LIJIAQI1999** [comment]
> Hi.
> 
> 1. For each text prompt, we generated 9 shapes, because we not only report the generation quality but diversity as well.
> 2. It's 500. It's only a subset of official test splits. Because evaluating on the whole ShapeGlot is costly for us.
> 3. I use the same hyperparameters in the default config of `eval_textdf.py`.
> 
> I guess the different metric values come from the different test subset samples. We use a random seed to select the first 500 samples in the test split of ShapeGlot to evaluate our model and baselines. I could provide the detailed text subset we use if you need it.
> 
> Besides, even with the same test subset and hyperparameters, it's still possible to get slightly different results due to randomness in the diffusing process.

Thanks a lot! 
The detailed text subset is what I need and will help a lot. 
Apprecitate it so much.

**Comment by LIJIAQI1999** [comment]
Hi, Yuhan!
We successfully get metrics value close to the paper. 
Thanks a lot !
