### ISSUE TITLE
Why do we need the function unfold_to_cubes?

### ISSUE THREAD

**Issue by OswaldoBornemann** [colorful-liyu/3DQD#6]
Why do we need the function unfold_to_cubes?

**Comment by colorful-liyu** [comment]
The input shape is represented in the form of SDF grids (64 x 64 x 64). However, due to the computational limit,  we cannot encode the 64 x 64 x 64 grids at once. So we divide the whole shape into patches of 8 x 8 x 8, and separately encode them. That's what the function unfold_to_cubes is doing. For more details, please read paper sec3.1.

**Comment by OswaldoBornemann** [comment]
Oh, i see. So may I ask one more question? I have my own 3D point cloud dataset, which is not the Shapenet. So how can I transform it into SDF form? Thanks.

**Comment by colorful-liyu** [comment]
> 


In general, to extract the Signed Distance Function (SDF), you would typically start by converting the point cloud into a mesh and making it watertight. Then, you can calculate the SDF values for the grids using libraries such as CuBVH. For more specific code implementation, you may refer to works that are more focused on SDF reconstruction.

**Comment by OswaldoBornemann** [comment]
Thanks a lot. However, my dataset is not an object-kind dataset. It's more like a lidar kind dataset. So I wonder whether it is proper to convert it into a mesh form.

**Comment by colorful-liyu** [comment]
> 

I'm not sure. This is beyond my scope of knowledge.

**Comment by OswaldoBornemann** [comment]
Thanks a lot.
